export const MUTATION_KEYS = Object.freeze({
  ADD_CATEGORY: ["ADD_CATEGORY"],
  EDIT_CATEGORY: ["EDIT_CATEGORY"],
  DELETE_CATEGORY: ["DELETE_CATEGORY"],
  ADD_TRANSACTION: ["ADD_TRANSACTION"],
  EDIT_TRANSACTION: ["EDIT_TRANSACTION"],
  DELETE_TRANSACTION: ["DELETE_TRANSACTION"],
});
